### ISSUE TITLE
Conda Forge

### ISSUE THREAD

**Issue by thewchan** [juftin/camply#117]
Hello! I have successfully put this package on to Conda Forge, and I am extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/camply-feedstock

**Comment by juftin** [comment]
oooh, this is super neat @thewchan, thanks for adding that 👏 . Not being super familiar with maintaining conda forge packages - how can I help with maintenance on the conda side?

**Comment by thewchan** [comment]
@juftin Thanks! Very little work is involved at this point as I've done the leg work to get the package online in Conda, as maintainers we would just need to check when the bots make PR to update the package (happens when new updates are pushed to PyPI upstream) and merge when all tests are passed. If tests don't pass usually it's due to a need to update dependency requirements as well, but updating the recipe is easy and self explanatory. Let me know if you'd like to be a co-maintainer there!

**Comment by juftin** [comment]
Hey @thewchan - sorry for the late response. Yep, please add me on that. I'll coordinate an approval with my releases
