### ISSUE TITLE
Add client support for APIs that require javascript and recent user agents

### ISSUE THREAD

**Issue by acaloiaro** [juftin/camply#178]
**Is your feature request related to a problem? Please describe.**
Some providers require up to date user agents to be presented or javascript to be available when making API requests. Let's investigate how to concisely present recent browser user agents and present the presence of javascript when making API requests to providers. 

**Describe the solution you'd like**
- All client requests rotate through a list of recent (Last two major versions) browser agents when setting the `User-Agent` header 
- All client requests support javascript (or at least meet the requirement that javascript is enabled)

A strong contender for providing this support: https://github.com/psf/requests-html

**Describe alternatives you've considered**
N/A

**Additional context**
#177

**Comment by SoccerCore11** [comment]
FYI - I did some light testing with Selenium and https://github.com/ultrafunkamsterdam/undetected-chromedriver and tried to prevent the captcha for the Michigan site and was unsuccessful. I verified that JavaScript was enabled in the browser session.

**Comment by acaloiaro** [comment]
Per discussion on Discord and #209, I'm closing this issue.
