### ISSUE TITLE
Notifications for closed campsites

### ISSUE THREAD

**Issue by gaelollivier** [juftin/camply#243]
Hi 👋

First of all, thanks for maintaining this project. I just started using it recently and I’m very excited at the idea of potentially finding a campsite!

I just ran into a problem today: I’m getting notified for campsites, but the notification says « Availability status: closed » and on recreation.gov, the campsites show as « unavailable ».

Here’s the command I’m using:
```
camply campsites \
    --campground 232450 \
    --campground 232449 \
    --campground 232447 \
    --start-date 2023-07-21 \
    --end-date 2023-08-13 \
    --notifications slack \
    --search-forever
```

And an example campsite that is being returned: https://www.recreation.gov/camping/campsites/947

![6D3B31BE-BC81-4A76-B08B-0344DE932567](https://user-images.githubusercontent.com/2292908/233680725-c11bdb9d-55f0-42e2-91eb-f7a2446ae75b.jpeg)

**Comment by gaelollivier** [comment]
Looking at the code, I suspect the API might be returning a new status that isn’t being handled by [CAMPSITE_UNAVAILABLE_STRINGS](https://github.com/juftin/camply/blob/919b9e9d60cfbef1af77bcac895ef3889fe94b03/camply/providers/recreation_dot_gov/recdotgov_camps.py#L191).

One suggestion I can think of to make this more robust: instead of using a deny list for the list of codes that are considered unavailable, could this be changed to an allow list of codes for available statuses?
Alternatively, if you’re worried of false negatives, one option could be to add a list of `KNOWN_AVAILABILITY_STATUSES`, that lists all the status codes that were seen before / are supported. If the script sees a code that it doesn’t know, then it could log it explicitly and maybe allow the list to be configured?

**Comment by juftin** [comment]
Missed this issue and just saw the PR instead before merging. Agreed, it would be nice to know a `KNOWN_AVAILABILITY_STATUSES`. [CAMPSITE_UNAVAILABLE_STRINGS](https://github.com/juftin/camply/blob/919b9e9d60cfbef1af77bcac895ef3889fe94b03/camply/providers/recreation_dot_gov/recdotgov_camps.py#L191) is early code. I'll take a look at optimizing this soon. Thanks for the contribution in the meantime!
