### ISSUE TITLE
Pinnacles Campground not supported

### ISSUE THREAD

**Issue by kekec** [juftin/camply#249]
Hi,

I was trying to run camply against pinnacles campground. For some reason I could not get this to work.
I have used the campground ID "234015" from recreation.gov camply could not find it.

`camply campsites     --rec-area 234015     --start-date 2023-07-10     --end-date 2023-07-18     --notifications silent     --search-forever`

Is my approach wrong?
Thank you!

**Comment by juftin** [comment]
Hey @kekec, you're close. Pinnacles Campground has **campground id** `234015` and **recreation area id** `2893` (Pinnacles National Park, CA). You'd provide a `--campground` arg instead of a `--rec-area` arg here:
```shell
camply campsites --campground 234015 --start-date 2023-07-10 --end-date 2023-07-18 --search-forever
```

**Comment by juftin** [comment]
No worries! Good luck getting a spot in July 🏕️
