### ISSUE TITLE
Notifications over MQTT?

### ISSUE THREAD

**Issue by brayStorm** [juftin/camply#266]
**Is your feature request related to a problem? Please describe.**
Greatly prefer local consumption of notifications.

**Describe the solution you'd like**
MQTT!

**Describe alternatives you've considered**

**Additional context**

**Comment by juftin** [comment]
MQTT is compatible via Apprise Notifications https://juftin.com/camply/command_line_usage/#send-a-notification-using-apprise-compatible-services

**Comment by juftin** [comment]
```
pipx install "camply[apprise]"
```

Your `APPRISE_URL` env variable / config entry would be in the following format:

```
mqtt://hostname/topic
mqtt://user@hostname/topic
mqtts://user:pass@hostname:9883/topic
```

**Comment by juftin** [comment]
Let me know what your experience is like with that.

```
export APPRISE_URL=xxxxxxxxxxxx
camply test-notifications --notifications apprise
```

**Comment by brayStorm** [comment]
I'm monitoring with MQTT Explorer. I've tried all the options for apprise under MQTT URL, and camply seems to send the test notification just fine, but I receive nothing on the MQTT feed. Any ideas?

**Comment by brayStorm** [comment]
`pipx install "camply[apprise]"` doesn't work, but `pipx install apprise` does. 🤷

**Comment by juftin** [comment]
Did you end up getting this to work @brayStorm? I noticed it's marked as closed.

**Comment by brayStorm** [comment]
Yes! Had to run `pipx install apprise`.
