### ISSUE TITLE
Support for novascotia.goingtocamp.com

### ISSUE THREAD

**Issue by brayStorm** [juftin/camply#267]
Appears to use the same standard api as the others.

**Comment by juftin** [comment]
@brayStorm Nova Scotia released! 🤝 

Let me know how it goes

**Comment by brayStorm** [comment]
I define the provider in yaml, but running `camply campsites --yaml-config camply_search.yaml` defaults the provider to RecreationDotGov.

If I include `--provider GoingToCamp`, it seems to work, but I'm getting no results:

![image](https://github.com/juftin/camply/assets/20567279/ef1fd596-a3e3-4c1f-ad48-966c3d35c709)

**Comment by juftin** [comment]
Alright @brayStorm another release was just published. It should resolve that YAML issue you're encountering. And, if it's helpful the new release also includes a [JSON Schema file for Camply Searches](https://github.com/juftin/camply/blob/main/docs/yaml_search.json)
