### ISSUE TITLE
Support for manitoba.goingtocamp.com

### ISSUE THREAD

**Issue by rpdids** [juftin/camply#282]
**Is your feature request related to a problem? Please describe.**
Manitoba parks booking service has migrated to goingtocamp and would be great to add into a future release 

**Describe the solution you'd like**
manitoba.goingtocamp.com supported by camply

**Describe alternatives you've considered**

**Additional context**
Very cool having a tool like this, great work!

**Comment by juftin** [comment]
Thanks for filing the issue. This is an easy one, not much code to write at all. Here's a similar implementation: https://github.com/juftin/camply/pull/277

I'm on an extended trip right now and will get to it when I'm back if someone doesn't implement it first
