### ISSUE TITLE
`POLLING_INTERVAL_MINIMUM` limit clarification

### ISSUE THREAD

**Issue by rtmlp** [juftin/camply#294]
Hi,

Why is the `POLLING_INTERVAL_MINIMUM` set to 5 minutes. Is it minimum interval suggested by the API provider ?

Thanks

**Comment by juftin** [comment]
The minimum polling interval is set to 5 minutes so we don't overload the APIs of our friends the booking providers.  but I've found the 5 minute limit to be reasonable and haven't heard any complaints yet from providers or users.

camply kind of skirts the edge on whether or not it is a tool that our providers approve of. There aren't any suggested limits or guidance from the API providers - so I like to err on the side of caution. 

Do you have a use case where you need to check more often than every 5 minutes?

**Comment by rtmlp** [comment]
Thanks a lot for the explanation. Makes lot of sense. 

My motivation for the question: I am using the personal API key and noticed that I received a notification for a campground through campflare which I missed through camply. So I got curious if the `POLLING_INTERVAL_MINIMUM` might have some influence on it and hence I asked the question

Does it make sense to edit/add the `POLLING_INTERVAL_MINIMUM` as environment variable ?

**Comment by juftin** [comment]
There isn't a polling interval minimum enforced on the RIDB API - this API is used to provide metadata about the campsites / recreation areas. Instead the polling interval is set on the "availability" API. For RecDotGov, the availability API is at https://www.recreation.gov/api/camps/availability and doesn't use API credentials. 

Camply will fan out across all of your selected campgrounds and search dates and make multiple requests to the API. After checking it then "sleeps" for the set `POLLING_INTERVAL` before trying again.

If campflare checks more often than 5 minutes it's possible a site became available and was booked in between camply's searches. Of course this is possible the other way around too where camply happens to search at the right interval to find something between campflare searches.

If you need to check more often than 5 minutes I would recommend [running camply as a cron job](https://juftin.com/camply/how_to_run/#search-once).

**Comment by rtmlp** [comment]
Thanks a lot for providing detailed explanation about API and the polling interval. For my use, your suggestion of running it as a cron job makes more sense. Thanks for pointing me towards this link
