### ISSUE TITLE
--start-date argument not getting respected

### ISSUE THREAD

**Issue by NiklasKK** [juftin/camply#318]
**Describe the bug**

The `--start-date` argument was not working as intended. I provided 2024-04-19 as start date, but received a Pushover notification for a night from the 17th to the 18th.

**Original Camply Command**
```console
camply campsites --campground 232447 --campground 232449 --start-date 2024-04-19 --end-date 2024-04-21 --notifications pushover --search-forever
```

**Expected behavior**

I expected to not get a notification for any nights before the 19th.

**Console Output (with `--debug`)**

No console output as I am running it in the background.

**Additional context**

This is a screenshot of the Pushover notification I received:

![IMG_FEB384CDA875-1](https://github.com/juftin/camply/assets/60063815/4add5e17-161d-4ce1-afba-624172cf8541)

**Comment by juftin** [comment]
Is this behavior consistent or intermittent?

**Comment by juftin** [comment]
Is this behavior consistent or intermittent?

**Comment by NiklasKK** [comment]
I'm pretty sure I saw it happen multiple times but sadly I deleted the Pushover notifications, but will definitely take another screenshot if I see it happening again.

**Comment by NiklasKK** [comment]
Yeah, you were right.
I actually had a copy paste error for my other search where I unintentionally pasted the 232447 campground.
So everything working correctly, sorry for the trouble 😄

**Comment by juftin** [comment]
Thanks for the follow up here!
