### ISSUE TITLE
"No campgrounds found to search" when using valid campground #

### ISSUE THREAD

**Issue by De-Brus** [juftin/camply#320]
I am getting the "no campgrounds found to search" when using a specific campground ID (232199). I even tried to scrape the rec area to see if the Luby Bay campground would show in the search results, which it did not. Are there some campgrounds that aren't able to be monitored even though they are offered on recreation.gov? 

camply campsites \
    --rec-area 232199 \
    --start-date 2024-08-01 \
    --end-date 2024-08-28 \
    --continuous \
    --notifications pushover \
    --notify-first-try --debug

I was expecting to scrape the website in hopes to catch a cancellation within my given window but get this error:

RuntimeError: camply encountered an error and exited 😟 [2024-02-03 15:06:05] - 
(SearchError) No campgrounds found to search

**Comment by juftin** [comment]
Hey @De-Brus I believe you're using a `--rec-area` argument instead of `--campground` - there isn't a rec area with ID # 232199.

`campground` # 232199 ([Luby Bay](https://www.recreation.gov/camping/campgrounds/232199)) is inside `rec-area` #1011 ([Idaho Panhandle National Forests](https://www.recreation.gov/camping/gateways/1011) )

```shell
camply campsites \
  --campground 232199 \
  --start-date 2024-08-01 \
  --end-date 2024-08-28
```

**Comment by De-Brus** [comment]
yes, you're right, thank you!! ok I think I have it working now.. 

So to do a continuous search with pushover notifications, I would use:

camply campsites \
  --campground 232199 \
  --start-date 2024-08-01 \
  --end-date 2024-08-28
  --continuous
  --notifications pushover

**Comment by juftin** [comment]
Yup, you might also want to pass the `--search-forever` option https://juftin.com/camply/command_line_usage/#continue-looking-after-the-first-match-is-found

**Comment by De-Brus** [comment]
Yes, thank you for clarifying. I believe I have it running properly now!
