### ISSUE TITLE
Provider Request: add support for `freecampsites.net`

### ISSUE THREAD

**Issue by pirate** [juftin/camply#323]
This is such a cool project!

It would be awesome if we could add support for FreeCampsites.net too:

https://freecampsites.net/

**Comment by juftin** [comment]
Thank you! Unfortunately [freecampsites.net](https://freecampsites.net) probably isn't a fit for camply as it doesn't manage any inventory / reservations. Camply's goal is to snag hard to find reservations at sold out campgrounds so it needs providers that manage inventory for a given date.
