### ISSUE TITLE
Is there a way to track event ticket?

### ISSUE THREAD

**Issue by DavydLiu** [juftin/camply#327]
**Is your feature request related to a problem? Please describe.**
Trying to get a reservation for going to sun road https://www.recreation.gov/timed-entry/10087086/ticket/10088646. But didn’t find a way to crawl this ticket.

**Describe the solution you'd like**
similar to scanning campsite for cancellation, it'd be awesome to be able to get notified if someone cancels their ticket.

**Describe alternatives you've considered*
Wake up earlier on the day the tickets released, but still failed to get any.

**Additional context**

**Comment by juftin** [comment]
Yes! Check it out here and let me know how it works

https://juftin.com/camply/command_line_usage/#searching-for-tickets-and-timed-entries

**Comment by juftin** [comment]
Closing as already completed
