### ISSUE TITLE
why is push disabled on your dockerbuild?

### ISSUE THREAD

**Issue by KyleSanderson** [juftin/camply#353]
**Describe the bug**

https://github.com/juftin/camply/blob/b110eea5992b57b0e84e1b350119b49230e6f574/.github/workflows/docker.yaml#L45

**Comment by juftin** [comment]
There are two docker image build in CI/CD. The one that you linked is a job titled `docker-ci-test` which is simply a test that ensures the image can built:

https://github.com/juftin/camply/blob/b110eea5992b57b0e84e1b350119b49230e6f574/.github/workflows/docker.yaml#L45

The second job is titled `docker-hub-publish` and is located in the `publish.yaml` workflow. This where the artifact is pushed after a release is generated:

https://github.com/juftin/camply/blob/6a00c1bc4ddd65e7b9ba06166042d5c32e874fcd/.github/workflows/publish.yaml#L72-L77

**Comment by juftin** [comment]
Yep, publishing to Docker Hub is part of the release process: https://hub.docker.com/r/juftin/camply

I'd consider using the GitHub Docker Container Registry, but would probably prefer just to use a single registry. Any reason why you prefer to pull an image from GitHub instead of Docker Hub?
