### ISSUE TITLE
Broken URL in notifications

### ISSUE THREAD

**Issue by rboarman** [juftin/camply#60]
When an alert fires for a Yellowstone site, Fishing Bridge in this case, the url included in the notification does not take you to the correct page.

This is the url that is generated:

https://secure.yellowstonenationalparklodges.com/booking/lodging-select/YLYF:RV?dateFrom=06-15-2022&nights=3

This url takes you to the general entrance page for booking a reservation. The date range is not entered on the page and the specific campground is not selected.

It looks like the site has changed their url structure.

**Comment by juftin** [comment]
Oh nice find @rboarman.

Looks like this is the new format: 

https://secure.yellowstonenationalparklodges.com/booking/lodging-select?dateFrom=06-15-2022&nights=3&destination=YLYF:RV&adults=1

Here's a fix for that: https://github.com/juftin/camply/pull/61

**Comment by juftin** [comment]
Resolved with https://github.com/juftin/camply/pull/61

Here's an example URL for Madison Campground: https://secure.yellowstonenationalparklodges.com/booking/lodging-select?dateFrom=10-15-2022&adults=1&destination=YLYM%3ARV&children=0&nights=1
