### ISSUE TITLE
Support Reserve California camp grounds

### ISSUE THREAD

**Issue by magic7s** [juftin/camply#67]
California Camp Grounds are in high demand and I'm looking for a way to get alerts when spots open up. California uses a separate system at https://www.reservecalifornia.com

I would love to see a new provider for Reserve California

Here is a project that supports reserve_ca https://github.com/awhitty/find-campsite

This looks like a great project and I hope to be able to use it soon. Thank you for the work!

**Comment by stjohnjohnson** [comment]
I'm _very_ interested in adding support for ReserveCalifornia.  Looks like it's quite different of a layout.

I'd be happy to start poking at this.  Any recommendation @juftin for how you would want this structured?

**Comment by juftin** [comment]
Oh very nice. Here's a very rough guide for implementing a new "Provider" with `camply`:

1) Implement a new `BaseCampingSearch ` class: https://github.com/juftin/camply/blob/7b64c22994d4c9472317230b59b98da98eb224b9/camply/search/base_search.py#L44
  - The `BaseCampingSearch` super class handles the high level interactions to do things like filter results to only weekends, look for consecutive nights, etc
  - This is an AbstractBaseClass that only requires you to define a single function: `get_all_campsites` which returns a list of `AvailableCampsite` data objects given the search parameters provided to the class
  - Here's an example of the Yellowstone implementation: https://github.com/juftin/camply/blob/7b64c22994d4c9472317230b59b98da98eb224b9/camply/search/search_yellowstone.py#L21

2) Embed a `BaseProvider` into the newly created search class - this is used inside the `BaseCampingSearch` instance to actually search and create the `camply.containers.AvailableCampsite` objects
 - This is the class where you define how to interact with the API of the Camping provider. 
 - Here's an example of the Yellowstone Provider: https://github.com/juftin/camply/blob/7b64c22994d4c9472317230b59b98da98eb224b9/camply/providers/xanterra/yellowstone_lodging.py#L29

Hopefully this makes sense - if I were to totally rewrite camply today I might structure it differently, so maybe there's a way to do this better. I'm happy to help put things together as progress gets closer on the `BaseProvider` class as well

**Comment by juftin** [comment]
Another note on how I parse results from the API: I use a custom `pydantic.BaseModel` class (`CamplyModel`) all over `camply` - it's a hashable data container class that defines core data containers like `AvailableCampsite` and `CampgroundFacility` but it also really helps to parse JSON responses from API's. Here's an example similar to what I'm doing in https://github.com/juftin/camply/blob/7b64c22994d4c9472317230b59b98da98eb224b9/camply/containers/api_responses.py. 


```python
import datetime
from enum import Enum
from typing import Dict

from camply.containers.base_container import CamplyModel

raw_campsite_api_response = {
    "campsite_id": "12345",
    "campsite_name": "example campsite",
    "campsite_availabilities": {
        "2022-03-05": "available",
        "2022-03-06": "unavailable",
        "2022-03-07": "unavailable",
        "2022-03-08": "unavailable",
        "2022-03-09": "available"
    },
    "campsite_location": "Anywhere, USA",
    "_non_useful_metadata_field": "sdcsad123431"

}


class ReserveCAAvailabilityOptions(str, Enum):
    available = "available"
    unavailable = "unavailable"


class ReserveCACampsiteResponse(CamplyModel):
    campsite_id: int
    campsite_name: str
    campsite_availabilities: Dict[datetime.date, ReserveCAAvailabilityOptions]
    campsite_location: str


easy_to_use_response = ReserveCACampsiteResponse(**raw_campsite_api_response)
```

That script defined our API response schema using `pydantic`, converted the raw dictionary into a data object using just the fields we defined, performed validation on the data provided and converted the string variables using python typing, and makes the data available in a way that's easy to code:
```python
for datetime_obj, status in easy_to_use_response.campsite_availabilities.items():
    if status == ReserveCAAvailabilityOptions.available:
        print(f"{datetime_obj.strftime('%Y-%m-%d')} is available for camping!")
```

**Comment by bryanwhiting** [comment]
👋 thanks for making Camply! I'm also interested in Reserve California. Any update on this?

**Comment by bryanwhiting** [comment]
Here's another scraper that uses reserve_ca: https://github.com/ggydush/campsites

**Comment by juftin** [comment]
At long last, I'm finally looking into implementing ReserveCalifornia. It's been tricky - but I've made some really amazing progress. https://github.com/ggydush/campsites has been super helpful - I ended up using a few APIs I haven't seen there or anywhere else as well. I'll have more to say here soon ✨
