### ISSUE TITLE
Help text typo for start_date

### ISSUE THREAD

**Issue by winfij** [juftin/camply#95]
The following help text has a typo: start_date vs start-date

```
[2022-07-11 15:43:50] ERROR    Campsite searches require the following mandatory search parameters: --start_date,
                               --end-date
```

**Comment by juftin** [comment]
Thanks @winfij . Looks like we have a fix lined up here: https://github.com/juftin/camply/pull/92

Let me see what I need to do to move this along

**Comment by juftin** [comment]
Yup, just merged the fix. Thanks for bug reporting!
